### ISSUE TITLE
Add network specific USE flags to the prepare script.

### ISSUE THREAD

**Issue by Nik--** [Jannik2099/gentoo-pinebookpro#3]
Since there are already parameters in the prepare.sh script that enable specific use flags, why not add network-specific use flags as well, since they are quite desired to have in most cases.

```diff
diff --git a/helpfile b/helpfile
index 8b30d8b..07a609b 100644
--- a/helpfile
+++ b/helpfile
@@ -4,4 +4,5 @@ option [default] description:
        -h,--help                                       display this help
        --gles2                 [yes]:                  use gles2 instead of OpenGL where applicable. recommended with panfrost
        --wayland               [no]:                   apply patches to allow use of wayland
+       --network               [no]:                   apply NetworkManager, wifi, bluetooth USE flags to enable network management.
        --zram                  [yes]:                  configure zram as swap. I heavily recommend this for Gentoo usage
diff --git a/prepare.sh b/prepare.sh
index ca12d72..8b2206d 100755
--- a/prepare.sh
+++ b/prepare.sh
@@ -37,6 +37,10 @@ while [ "${i}" -le "${j}" ]; do
                wayland=${2}
                ;;
 
+               --network)
+               network=${2}
+               ;;
+
                --zram)
                zram=${2}
                ;;
@@ -87,6 +91,11 @@ if [ "${wayland}" = "yes" ]; then
        echo "installed wayland profile patches. using wayland is NOT recommended right now!!!"
 fi
 
+if [ "${network}" = "yes" ]; then
+       sed -i "s/USE=\"/USE=\"networkmanager wifi bluetooth /" /etc/portage/make.conf
+       echo "installed network profile patches. You might want to install \"net-wireless/bluez\" for bluetooth management."
+fi
+
 if [ "${zram}" != "no" ]; then
        if [ "${init}" = "systemd" ]; then
                install -Dm 644 "${FILES}"/zram/zram0.service /etc/systemd/system/zram0.service
```

**Comment by Jannik2099** [comment]
This is a good idea, but I want to be careful in keeping the balance between required minimum to use the system and having everything ready from the go.

I think I'll implement this, and I am open for other suggestions.

**Comment by Nik--** [comment]
The script gave me the impression that since it has options for graphics and comforts such as zram, it would only be logical to have networking and other stuff that enable the pinebook pro's functionality.
As for ideas, I thought of a `touchpad` USE flag support, which enables synaptics in KDE, but thats only KDE specific, and I think this is where the line should be drawn. Maybe you can leave it in the readme as a suggestion or something. Sound support can be another thing, adding `pulseaudio` USE flag can help, but not everyone likes it and I don't know how good ALSA support is throughout the desktop environments.
If I find something else that the pinebook pro is lacking from the bare gentoo installation which cripples it in a way (like networking) I will write another suggestion.

**Comment by avanasear** [comment]
IMO the networkmanager USE flag is unnecessary to enable as a default USE flag. I use wpa_supplicant only, making the networkmanager flag extraneous. Similar situation with pulseaudio. IMO the networkmanager flag is only necessary if you're going to be using a DE which relies on it, or (obviously) if you're going to be using networkmanager.

**Comment by Jannik2099** [comment]
I've decided to remove both the wayland and gles2 useflag shenanigans: wayland wasn't platform specific in the first place, and gles2 is no longer necessary nor desirable.

We're working on mainlining parts of the overlay, and as such this should only contain workarounds that are required for the pbp (like gles2 used to be), not stuff that makes things more comfortable for the user (like wayland or networkmanager)
