### ISSUE TITLE
zram0 service doesn't work.

### ISSUE THREAD

**Issue by Nik--** [Jannik2099/gentoo-pinebookpro#4]
The provided zram service does not work.

```
$ rc-service zram0 start
 * Configure zram0 as swap...
zramctl: /dev/zram0: failed to set algorithm: Invalid argument
 * ERROR: zram0 failed to start
```

The algorithm its trying to set is **lzo_rle** while it should be **lzo-rle**

Apart from the main issue, I thought zram0 service enabled zram0 as swap as soon as you enable it, but it didn't appear to do so. It will be nice if you can include`mkswap /dev/zram0` and `swapon -p 32767 /dev/zram0` *(-p argument to set the zram to have higher priority than other swap)* into the service script.

**Comment by Nik--** [comment]
Here is the changed init script I'm currently using. You can use it right away, starting and stopping the service works accordingly.

```shell
#!/sbin/openrc-run

description="Configure zram0 as swap"

depend()
{
        provide zram0
        use dev-mount
        before dev
}

start()
{
        ebegin "Enabling zram0 as swap"
        # Adding a dummy `zramctl -f` command, which fixes a bug causing the service to fail to start after getting disabled once:
        # "zramctl: zram0: No such device"
        modprobe zram && zramctl -f && zramctl zram0 -s 12G -t 6 -a lzo-rle && mkswap /dev/zram0 && swapon /dev/zram0 -p 10
        eend $?
}

stop()
{
        ebegin "Disabling zram0 as swap"
        swapoff /dev/zram0 && zramctl -r zram0
        eend $?
}
```

**Comment by Jannik2099** [comment]
Oh god, has it been that way all the time? Kinda embarassing, thanks for the report!

Addendum: didn't know the commit line "fixed #issue" would auto-close an issue, interesting!
