### ISSUE TITLE
README.md could be clearer on downloading repo

### ISSUE THREAD

**Issue by Lady-Galadriel** [Jannik2099/gentoo-pinebookpro#5]
This is for the top level README.md file.

The instructions gloss over how to get the repo on your PBP;
```
Put the files of this repository into the tarball - preferably into /var/tmp/gentoo-pinebookpro Chroot into the tarball as 
```
Also missing a period after `/var/tmp/gentoo-pinebookpro`

I did figure it out, (my experience with GitHub is limited). I think this would suffice;
```
Put the files of this repository into the tarball - preferably into /var/tmp/gentoo-pinebookpro. You can download a ZIP file using the Repo "Clone or download" button and select Download ZIP. Put the ZIP file in /var/tmp and un-zip it. Rename it with;
mv gentoo-pinebookpro-master gentoo-pinebookpro
```
I'll try the rest of the instructions now. But, I figure one problem per issue.

Again, thanks for taking on this project. I really want to use Gentoo on my PBP.

**Comment by Jannik2099** [comment]
Yeah, the README definitely needs some work. However I first want to finalize the overlay before updating the README, and after that I'll call it a full release

Any feedback about the README is more than welcome!

**Comment by DamonLane** [comment]
Thanks for doing this and sharing your work. There's a typo in "sources" in the following sentence: "The Kernel ebuild sys-kernel/pinebookpro-manjaro-soruces has been added." under "Changes to the Gentoo repository"
